name: iOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Select Xcode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0'
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'
        channel: 'stable'
        cache: true
    
    - name: Install Flutter dependencies
      run: flutter pub get
      
    - name: Create iOS files
      run: |
        flutter create --platforms=ios .
        
    - name: Clean iOS build
      run: |
        cd ios
        rm -rf Pods
        rm -rf Podfile.lock
        cd ..
        
    - name: Install CocoaPods
      run: |
        sudo gem install cocoapods
        
    - name: Install CocoaPods dependencies
      run: |
        cd ios
        pod install
        cd ..
    
    - name: Build iOS
      run: |
        flutter build ios --release --no-codesign
    
    - name: Create IPA
      working-directory: build/ios/iphoneos
      run: |
        mkdir Payload
        cp -r Runner.app Payload
        zip -r app.ipa Payload
    
    - name: Upload IPA
      uses: actions/upload-artifact@v3
      with:
        name: ios-build
        path: build/ios/iphoneos/app.ipa