name: iOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: macos-latest  # Required for iOS builds
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Select Xcode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0'
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'
        channel: 'stable'
        cache: true
    
    - name: Install Flutter dependencies
      run: flutter pub get
    
    - name: Install CocoaPods dependencies
      working-directory: ios
      run: pod install
    
    - name: Build iOS
      run: |
        flutter build ios --release --no-codesign
    
    - name: Create IPA
      working-directory: build/ios/iphoneos
      run: |
        mkdir Payload
        cp -r Runner.app Payload
        zip -r app.ipa Payload
    
    - name: Upload IPA
      uses: actions/upload-artifact@v3
      with:
        name: ios-build
        path: build/ios/iphoneos/app.ipa 